### ISSUE TITLE
The detail RTK user connection description should be clarified in the quick start 

### ISSUE THREAD

**Issue by yifanff** [Aceinna/docs_openrtk#3]
![2020-11-23_15h32_22](https://user-images.githubusercontent.com/5958693/99941133-783dbe00-2da8-11eb-95a2-eb7787d63e87.jpg)
'Boot mode swtich, with two positions (A, B) to select from', should clarify the position A, B usage to customer. 

![2020-11-23_15h33_33](https://user-images.githubusercontent.com/5958693/99941183-8ab7f780-2da8-11eb-80b2-3458120aec64.jpg)
'RJ45 jack for Ethernet connection',  should clarify:
1.Where could customer get the location service used on RTK.
2.The uart interface usage for ethernet connection.

**Comment by banana0821** [comment]
![1649209526(1)](https://user-images.githubusercontent.com/49057987/161879043-8c024505-f832-40de-9264-5e7dec2782cf.jpg)
Question:'Boot mode swtich, with two positions (A, B) to select from', should clarify the position A, B usage to customer.
Answer:Positions (A, B) are clarified in Quick Start as shown in the figure above;

![1649210098(1)](https://user-images.githubusercontent.com/49057987/161880101-957de905-aaec-490f-bdde-f65705203d89.jpg)
Question:'RJ45 jack for Ethernet connection', should clarify:
1.Where could customer get the location service used on RTK.
2.The uart interface usage for ethernet connection.
Answer:1.How to get the location service used on RTK is shown in Quick Start as shown in the figure above. 
             2.Ethernet pin clarify:RMII_TXD0(#9),RMII_RMII_TXD1(#10) 
                                              RMII_RXD0(#16),RMII_RXD1(#14)

**Comment by banana0821** [comment]
close #3
