### ISSUE TITLE
User antenna selection recommendation

### ISSUE THREAD

**Issue by yifanff** [Aceinna/docs_openrtk#4]
Should give user advice about the antenna brand selection, regarding to the detail of Multi-Constellation Multi-frequency GNSS antenna, to make sure have a better test result.

**Comment by banana0821** [comment]
![image](https://user-images.githubusercontent.com/49057987/161887083-d5fc84fd-3c35-41e6-a114-c23139beef8d.png)
The GNSS antenna we provide supports GPS、GLONASS、GALILEO and BEIDOU.The function fully meets the test requirements.
