### ISSUE TITLE
CAN msg error(Should confirm the Get specified parameters, the PDU format and PDU specific)

### ISSUE THREAD

**Issue by yifanff** [Aceinna/docs_openrtk#6]
![image](https://user-images.githubusercontent.com/5958693/100205325-eff22100-2f3f-11eb-8fcc-21c3f2320f8b.png)

**Comment by banana0821** [comment]
![image](https://user-images.githubusercontent.com/49057987/161885910-c5519d53-6e15-4aeb-ac91-f593f4900794.png)
Include software version number、ECU ID、CAN packet type、CAN data frequency and so on.PF and PS of specific parameters are already introduced.
